export const ROLE_NAMES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  FACULTY: 'FACULTY',
  STUDENT: 'STUDENT',
} as const;

export const PERMISSION_NAMES = {
  CREATE_USERS: 'CREATE_USERS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  READ_LOGS: 'READ_LOGS',
  // --- Academic Scopes ---
  MANAGE_ACADEMICS: 'MANAGE_ACADEMICS',
  MANAGE_CALENDAR: 'MANAGE_CALENDAR',
  MANAGE_TIMETABLES: 'MANAGE_TIMETABLES',
} as const;

export type PermissionName =
  (typeof PERMISSION_NAMES)[keyof typeof PERMISSION_NAMES];
